### ISSUE TITLE
Draft a working agreement

### ISSUE THREAD

**Issue by cdata** [omigroup/omi-wasm-group#1]
It seems like the next step for this group is to draft a working agreement. There is a good standing example to be found here: https://github.com/omigroup/gltf-extensions#working-agreement

Can we organize a meeting for folks tentatively interested in participating in this group to draft a working agreement?

**Comment by robertlong** [comment]
Yes, let's definitely get that meeting scheduled. We're trying to find a time in our Discord https://discord.gg/ZXDyTsQBqu in the #omi-wasm-group channel.

Also I have some things I'd personally like to see in the creation of this group. I think we should strictly adhere to the W3C Community Group process so that we can be set up for success in getting on the standards track. This means we need to be strict about recording, CLA, taking notes, etc. I also think we should set up the [W3C spec publishing Github Action](https://github.com/w3c/spec-prod) and make sure we're using the official W3C template and ReSpec/Bikeshed. All of this means we can better integrate with the tools/processes that W3C has already created. It ensures we have proper IP protection as well.

**Comment by mrmetaverse** [comment]
Bump - do we have a working agreement defined yet? @cdata

**Comment by mrmetaverse** [comment]
Hey all! Came across this during grooming today, and wanted to check in. Have you put together a working agreement already? If not, I am happy to help guide a 30 min discussion to put one together to get this group started.

**Comment by robertlong** [comment]
We've added a working agreement in https://github.com/omigroup/omi-wasm-group/pull/25
